### ISSUE TITLE
MacOS only?

### ISSUE THREAD

**Issue by Datou** [OpenGenerativeAI/llm-colosseum#24]
Downloading pyobjc-core-10.2.tar.gz (929 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 929.8/929.8 kB 14.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      running egg_info
      error: PyObjC requires macOS to build
      [end of output]

**Comment by moritz-august** [comment]
I simply commented out the respective two lines in the requirements.txt and does work nonetheless under Debian 12 for me.

**Comment by oulianov** [comment]
Good catch! I removed these two requirements from requirements.txt
