### ISSUE TITLE
.diambra/roms does not exist.

### ISSUE THREAD

**Issue by taozhiyuai** [OpenGenerativeAI/llm-colosseum#27]
when I try to save ROM to ~/.diambra/roms, it does not exist. what should I do? my laptop is Macbook. 

`(streetfighter) taozhiyu@TAOZHIYUs-MBP llm-colosseum % open ~/.diambra/roms
The file /Users/taozhiyu/.diambra/roms does not exist.`

**Comment by StanGirard** [comment]
Download this rom only if you own the physical instance ;) 

https://wowroms.com/en/roms/mame/street-fighter-iii-3rd-strike-fight-for-the-futur-japan-clone/106255.html

**Comment by taozhiyuai** [comment]
> Download this rom only if you own the physical instance ;)
> 
> https://wowroms.com/en/roms/mame/street-fighter-iii-3rd-strike-fight-for-the-futur-japan-clone/106255.html

can I use this rom?
https://www.allmyroms.net/AllMyRoms.php?page=view-download&jeu=kof98umh.zip&titre=Arcade

**Comment by oulianov** [comment]
Diambra checks for a hash of the ROM to verify its integrity. We made tests and only the one on wowroms worked for us.
Not sure if another one will do the trick !

**Comment by taozhiyuai** [comment]
> I don't think so. Diambra checks for a hash of the ROM to verify its integrity. If you have another ROM file which has a different hash, the game won't load. We made tests and only the one on wowroms worked for us. Not sure if another one will do the trick !

thx
