### ISSUE TITLE
Unset API keys are not handled properly

### ISSUE THREAD

**Issue by moritz-august** [OpenGenerativeAI/llm-colosseum#29]
I noticed that in the current main branch, mistral is always activated by default. That of course causes a problem if the API key is not actually set. Similar case also for the OpenAI key.

In you case you don't already have a fix for that in some branch, I could create a PR for that.

**Comment by StanGirard** [comment]
Would love to get a PR to fix that :)

**Comment by oulianov** [comment]
Good catch. I edited the config. Now, there will be an error about env API_KEY not set only if you are trying to use this provider.

Let me know if you managed to make it work for you!

**Comment by moritz-august** [comment]
Thanks! Yes, I made that work for me by simply setting the default for mistral to false in the game __init__. Cool, then I guess I don't need to make a PR anymore after all :)
