### ISSUE TITLE
Issue while trying to run locally

### ISSUE THREAD

**Issue by edgmin** [OpenGenerativeAI/llm-colosseum#49]
Hello!
First, thank you for the interesting project!
I am trying to run it locally with ollama using an anaconda environment. However, I am getting the following error:

File "\llmtest\llm-colosseum\agent\robot.py", line 135, in plan
KeyError: 12
    next_buttons_to_press = [
  File "\llmtest\llm-colosseum\agent\robot.py", line 138, in <listcomp>
    for button in META_INSTRUCTIONS_WITH_LOWER[combo][self.current_direction.lower()]
KeyError: 6

Context: The game window appears, but the characters do not do anything. 

Any idea on what is happening here?

**Comment by taozhiyuai** [comment]
read all my issues. it is done!

**Comment by mengxiyou** [comment]
there is a bug maybe.
robot.py:290,I changed the code from
return [random.choice(list(MOVES.values()))]
to
return [random.choice(list(META_INSTRUCTIONS_WITH_LOWER.keys())).lower()]

and it works.

**Comment by taozhiyuai** [comment]
it works for me . no modification is requested.

**Comment by edgmin** [comment]
> there is a bug maybe. robot.py:290,I changed the code from return [random.choice(list(MOVES.values()))] to return [random.choice(list(META_INSTRUCTIONS_WITH_LOWER.keys())).lower()]
> 
> and it works.

Thank you! This completely solved my problem!
