### ISSUE TITLE
can't fetch new commit

### ISSUE THREAD

**Issue by taozhiyuai** [OpenGenerativeAI/llm-colosseum#54]
look. GitHub desktop version can not get your latest commit

<img width="1583" alt="截屏2024-05-10 20 38 36" src="https://github.com/OpenGenerativeAI/llm-colosseum/assets/146583103/5a4c154f-e3b8-46e4-acaf-f5ab8e157da4">
![WX20240510-203802@2x](https://github.com/OpenGenerativeAI/llm-colosseum/assets/146583103/9ab3dcf4-e82e-46f7-9a3b-54a5284c9a96)

**Comment by oulianov** [comment]
Sounds like an issue with your computer...

My recommendation ? Just delete your local folder and run `git clone` again. 👍
