### ISSUE TITLE
Project no more maintained?

### ISSUE THREAD

**Issue by HakaishinShwet** [OpenGenerativeAI/llm-colosseum#57]
?

**Comment by StanGirard** [comment]
Yes it is ;) But what more do we need ?

**Comment by HakaishinShwet** [comment]
more games? ;-))

**Comment by oulianov** [comment]
For more games and more algorithms, you can look into [Diambra](https://diambra.ai), which is an awesome open source project !

If you wish to push new features, feel free to open a PR. I come back at least once a month to make sure things are in order :)
