### ISSUE TITLE
Fighters not fighting

### ISSUE THREAD

**Issue by nickschuetz** [OpenGenerativeAI/llm-colosseum#60]
Despite following the instructions on how to run llm-colosseum in the README and trying `make run` , `make local` and `make demo` executions (still following instructions exactly) the window pops up and the players just sit there and the clock ticks to zero. Then the console defaults to Player 1 always winning despite no actual winners. What am I not doing or doing wrong?

P.S. Is there a Discord for this project?

**Comment by nickschuetz** [comment]
Here's the output i'm seeing in the terminal
```
🏟️  (b18f) (0)Starting game
🏟️  (b18f) (0)Waiting for fight to start
2024-08-07 09:37:46.525 Python[54119:2568961] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    self.run()
  File "/Users/ken/PROJECTS/DIAMBRA/llm-colosseum/eval/game.py", line 369, in run
  File "/Users/ken/PROJECTS/DIAMBRA/llm-colosseum/eval/game.py", line 383, in run
    self.game.player_2.robot.plan()
  File "/Users/ken/PROJECTS/DIAMBRA/llm-colosseum/agent/robot.py", line 134, in plan
    self.game.player_1.robot.plan()
  File "/Users/ken/PROJECTS/DIAMBRA/llm-colosseum/agent/robot.py", line 134, in plan
    next_steps_from_llm = self.get_moves_from_llm()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/PROJECTS/DIAMBRA/llm-colosseum/agent/robot.py", line 293, in get_moves_from_llm
    next_steps_from_llm = self.get_moves_from_llm()
    llm_stream = self.call_llm()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ken/PROJECTS/DIAMBRA/llm-colosseum/agent/robot.py", line 293, in get_moves_from_llm
                 ^^^^^^^^^^^^^^^
  File "/Users/ken/PROJECTS/DIAMBRA/llm-colosseum/agent/robot.py", line 369, in call_llm
    llm_stream = self.call_llm()
                 ^^^^^^^^^^^^^^^
  File "/Users/ken/PROJECTS/DIAMBRA/llm-colosseum/agent/robot.py", line 369, in call_llm
    resp = client.stream_chat(messages)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stream_chat'
    resp = client.stream_chat(messages)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'stream_chat'
🏟️  (b18f) (0)Round won by P1
(0)Moving to next round
 Player1 mistral:mistral-small-latest 'Baby' won!
🏟️  (b18f) Closing console
🏟️  (b18f) (0)----------------------------------------
(0)   Thank you for using DIAMBRA Arena.
(0)   RL is the main road torwards AGI,
(0) better to be prepared... Keep rocking!
(0)                   -
🏟️  (b18f) (0)          https://diambra.ai
(0)----------------------------------------
```

**Comment by oulianov** [comment]
Hello ! 

Looks like this error was related to : https://github.com/OpenGenerativeAI/llm-colosseum/issues/62 
I pushed your suggested fix : renaming ollama.py to local.py
Thank you for figuring this out ! 

For the Discord, we hang out on the [Diambra](https://diambra.ai) Discord : https://discord.com/invite/jDcW8z4gft
My user tag is roger_jacques

**Comment by nickschuetz** [comment]
#62 does fix the issue for `make local`. However, the issue still remains when using remote models.

**Comment by oulianov** [comment]
What is the error message you encounter when using remote models ?
Client is also None ?

**Comment by nickschuetz** [comment]
> What is the error message you see when using remote models ? `AttributeError: 'NoneType' object has no attribute 'stream_chat'` ?

Yes, that's the one.

**Comment by oulianov** [comment]
Okay, I understand now.

This is my fault, I merged a PR 5 months ago that refacto'd this and removed `mistral` from the list of supported models. I changed this on main https://github.com/OpenGenerativeAI/llm-colosseum/pull/68

Can you please follow the following instructions:
0. Fetch the latest version `git checkout main`, then `git pull`
1. Create a new python virutal environment `python -m venv env`
2. Activate the env `source env/bin/activate` (if you're on Windows, the command is different)
3. Install requirements with `make install`. If this doesn't work, do `pip install -r requirements.txt`
4. Try first to run with openai: `make run` (You need to create a `.env` file with an OpenAI API key, and you need Docker installed and running)
5. Launch Ollama locally (`ollama`), install the mistral model (`ollama run mistral`), then run `make local` to launch local version

Tried all of this on my machine and it worked fine. 
So I'm not sure which step actually fails for you. 
As you see, there is a lot of setup and Python gotchas. 

Please tell me if it works now. If it still fails, please tell me at which step.

Feel free to book a call with me here: https://cal.com/nicolas-oulianov 
We'll get to the bottom of this!!!!!

**Comment by nickschuetz** [comment]
I cannot currently test the `make run` against the gpt-4o models defined in [script.py](https://github.com/OpenGenerativeAI/llm-colosseum/blob/main/script.py#L15-L23) but the `make local` works. Do you know anyone else that can test the `make run`?

Also note that [Podman](https://podman.io/) works as a great open source alternative to Docker. That's what I've been using.

**Comment by nickschuetz** [comment]
I'm getting this error when running `make demo`:

```
ModuleNotFoundError: No module named 'llama_index.llms.mistralai'
    from llama_index.llms.mistralai import MistralAI
ModuleNotFoundError: No module named 'llama_index.llms.mistralai'
2024-09-16 18:51:54.698 Python[60482:257677] +[IMKClient subclass]: chose IMKClient_Legacy
2024-09-16 18:51:54.698 Python[60482:257677] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
```

**Comment by oulianov** [comment]
Did you run `make install` before running `make demo` ?

From the error, you are missing the package `llama-index-llms-mistralai`. Running `make install` will install it for you

**Comment by nickschuetz** [comment]
> Did you run `make install` before running `make demo` ?
> 
> From the error, you are missing the package `llama-index-llms-mistralai`. Running `make install` will install it for you

Good catch it was the lack of `make install`. Somehow I got caught with a new venv and didn't do the install again. So I got `make demo` to work but ran into a paywall with the Free Mistral tier:

```INFO:httpx:HTTP Request: POST https://api.mistral.ai/v1/chat/completions#stream "HTTP/1.1 429 Too Many Requests"```
