### ISSUE TITLE
ImportError: cannot import name 'Client' from 'ollama' 

### ISSUE THREAD

**Issue by nickschuetz** [OpenGenerativeAI/llm-colosseum#62]
When running models locally using `ollama` and utilizing the `ollama.py` as an input script to `diambra` it fails with the following error:

`ImportError: cannot import name 'Client' from 'ollama' (/home/ken/PROJECTS/llm-colosseum/ollama.py)`

If you rename `ollama.py` to something like `local.py` and run it that way it works.

Ref: https://github.com/ollama/ollama-python/issues/91#issuecomment-2025819852

**Comment by oulianov** [comment]
Good catch ! https://github.com/OpenGenerativeAI/llm-colosseum/pull/65
